spring:
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
        show_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  datasource:
    url: jdbc:mysql://ec2-52-79-52-23.ap-northeast-2.compute.amazonaws.com:3306/main28
    username: seb45
    password: Seb45_main28
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
h2:
  console:
    enabled: false

jwt:
  access-token-expiration-minutes: 60
  refresh-token-expiration-minutes: 120

cloud:
  aws:
    credentials.access-key: ${S3_ACCESS_KEY}
    credentials.secret-key: ${S3_SECRET_KEY}
    s3.bucket: 28be
    region.static: ap-northeast-2
    stack.auto: false